/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/newScene.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Campfire"
          castShadow
          receiveShadow
          geometry={nodes.Campfire.geometry}
          material={materials.Campfire_MAT}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.04}
        />
      </group>
    </group>
  );
}

export default Model;

useGLTF.preload("/models/newScene.glb");
